FROM kalilinux/kali-rolling:latest

RUN apt update

RUN apt install -y \
    kali-tools-social-engineering \
    kali-tools-forensics \
    spiderfoot \
    theharvester \
    emailharvester \
    nikto \
    zmap \
    wpscan \
    gobuster \
    masscan \
    recon-ng \
    sherlock \
    eyewitness \
    dnsrecon \
    tcpdump \
    dirbuster \
    legion \
    dnsenum \
    ffuf \
    dirsearch \
    dnschef \
    snort \
    wordlistraider \
    wordlists
