FROM kalilinux/kali-rolling:latest

RUN apt update && \
    apt install -y && \
    spiderfoot && \
    theharvester && \
    emailharvester && \
    nikto && \
    zmap && \
    wpscan && \
    burpsuite && \
    gobuster && \
    masscan && \
    netcat && \
    john-data && \
    recon-ng && \
    wireshark && \
    sherlock && \
    eyewitness && \
    dnsrecon && \
    tcpdump && \
    dirbuster && \
    legion && \
    dnsenum && \
    ffuf && \
    maltego && \
    dirsearch && \
    mimikatz && \
    dnschef && \
    snort && \
    wordlistraider && \
    wordlists
