#!/bin/bash

set -e

echo "Add Stacheldrath Linux default user to docker group..."
gpasswd -a stacheldrath docker

echo "Starting Stacheldrath Linux compose stack..."
docker-compose -f /home/stacheldrath/.compose/docker-compose.yml up -d

exit 0
