#!/bin/bash

set -e

echo "Set permissions to stacheldrath user..."
chown stacheldrath:stacheldrath -R /home/stacheldrath/.compose

echo "Add Stacheldrath Linux default user to docker group..."
gpasswd -a stacheldrath docker

echo "Starting Stacheldrath Linux compose stack..."
docker-compose -f /home/stacheldrath/.compose/docker-compose.yml up -d

exit 0
